export {
  diffIR,
  generateTypeScriptMCPServer,
  inferIRFromDocs,
  isEndpointTool,
  isWorkflowTool,
  optimizeIRWithAI,
  parseOpenAPISpec,
  planWorkflowTools,
  scrapeDocsFromUrl,
  toJsonSchema,
  toStructuredOutputSchema,
  truncateText,
} from "@mcpforge/core";

export type {
  DiffChange,
  DiffResult,
  AuthConfig,
  EndpointToolDefinition,
  MCPForgeIR,
  OptimizerMode,
  RegistryEntry,
  RegistryIndex,
  RegistryIndexEntry,
  ResponseDef,
  ScrapedDocPage,
  ToolDefinition,
  WorkflowToolDefinition,
} from "@mcpforge/core";
